<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css"/>
<style>
    {
        button{
            position:absolute;
            top:1.21in;
            left:1.27in;
            width:1.43in;
            height:0.28in
        }
    }
</style>
</head>
<body>
<img style="position:absolute;top:0.00in;left:0.00in;width:9.02in;height:12.76in" src="vi_1.png" />
<div style="position:absolute;top:1.73in;left:2.88in;width:3.30in;line-height:0.36in;"><span style="font-style:normal;font-weight:bold;font-size:18pt;font-family:Times New Roman;color:#000000">MEDICAL CERTIFICATE</span><span style="font-style:normal;font-weight:bold;font-size:18pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.46in;left:6.23in;width:1.56in;line-height:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"> <input type="date" maxleth="18" align="center" id="input" name="input" class="input" placeholder="placeholder" style="border:0;outline:none;width:100%;height:100%;font-size:15px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.72in;left:6.83in;width:0.42in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">DATE</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.33in;left:1.09in;width:1.81in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">This is to certify that Mr</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times New Roman;color:#000000">./</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times New Roman;color:#000000">Ms.</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.71in;left:2.18in;width:5.01in;line-height:0.24in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Times New Roman;color:#000000"> <input type="text" maxleth="18" align="center" id="input" name="input" class="input" placeholder="Names" style="border:0;outline:none;width:100%;height:1000%;font-size:25px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.16in;left:1.09in;width:0.86in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">Date Examined <input type="date" maxleth="50" align="center" id="input" name="input" class="input" placeholder="placeholder" style="border:0;outline:none;width:100%;height:100%;font-size:15px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.34in;left:3.27in;width:1.14in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times New Roman;color:#000000">DATE EXAMINED</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.81in;left:1.09in;width:3.36in;line-height:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000">With the following findings and/or diagnosis:<input type="input" maxleth="18" align="center" id="input" name="input" class="input" placeholder="Diagnosis" style="border:0;outline:none;width:100%;height:auto;font-size:25px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.06in;left:1.64in;width:0.97in;line-height:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000">REMARKS:<input type="input" maxleth="100" align="center" id="input" name="input" class="input" placeholder="Remarks" style="border:0;outline:none;width:300%;height:100%;font-size:15px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.02in;left:1.09in;width:2.34in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">And would need medical attention for</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.00in;left:3.54in;width:1.42in;line-height:0.22in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Times New Roman;color:#000000"><input type="input" maxleth="18" align="center" id="input" name="input" class="input" placeholder="NOT APPLICABLE" style="border:0;outline:none;width:100%;height:auto;font-size:14px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.02in;left:5.14in;width:1.40in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">barring complications.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.54in;left:1.09in;width:1.29in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">Purpose of Issuance:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.51in;left:2.73in;width:2.43in;line-height:0.24in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Times New Roman;color:#000000">FOR HEALTH CLEARANCE</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:1.09in;width:3.53in;line-height:0.18in;"><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:Times New Roman;color:#000000">This Certification is valid for only 7 days upon date of issuance.</span><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.82in;left:3.77in;width:4.14in;line-height:0.24in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Times New Roman;color:#000000">AARON JESS KHALIL G. CURAY, RN, MD, MPM</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.02in;left:4.36in;width:2.95in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">Attending Physician – Municipal Health Officer</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/><DIV style="position:relative; left:0.55in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">License Number:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.05in;left:1.09in;width:0.78in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">OR Number: <input type="number" maxleth="18" align="center" id="input" name="input" class="input" placeholder="OR Number" style="border:0;outline:none;width:100%;height:auto;font-size:10px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.05in;left:2.18in;width:0.08in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.39in;left:1.09in;width:1.17in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">Date of Issuance <input type="date" maxleth="18" align="center" id="input" name="input" class="input"  style="border:0;outline:none;width:100%;height:auto;font-size:10px;text-align: center;" autocomplete="off" autofocus></span></SPAN><br/></div>
<div style="position:absolute;top:11.39in;left:1.09in;width:1.17in;line-height:0.20in;"><DIV style="position:relative; left:1.09in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.74in;left:1.09in;width:0.53in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">Amount<input type="input" maxleth="100" align="center" id="input" name="input" class="input" placeholder="Amount" style="border:0;outline:none;width:300%;height:100%;font-size:12px;text-align: center;" autocomplete="off" autofocus></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Times New Roman;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.74in;left:2.18in;width:0.08in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Times New Roman;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:180pt;font-family:Times New Roman;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:7.68in;left:2.72in;width:2.41in;height:0.02in" src="vi_2.png" />
<img style="position:absolute;top:0.27in;left:2.12in;width:4.84in;height:0.82in" src="ri_1.png" />
<img style="position:absolute;top:0.24in;left:1.28in;width:0.76in;height:0.73in" src="ri_2.png" />
<img style="position:absolute;top:0.17in;left:3.08in;width:2.94in;height:0.28in" src="ri_3.png" />
<img style="position:absolute;top:0.10in;left:6.91in;width:0.96in;height:1.00in" src="ri_4.png" />
<img style="position:absolute;top:1.08in;left:1.19in;width:6.88in;height:0.02in" src="ri_5.png" />
<img style="position:absolute;top:0.89in;left:2.01in;width:4.98in;height:0.28in" src="ri_6.png" />
<img style="position:absolute;top:2.66in;left:6.19in;width:1.56in;height:0.01in" src="ri_7.png" />
<img style="position:absolute;top:3.97in;left:1.09in;width:7.26in;height:0.01in" src="ri_8.png" />
<img style="position:absolute;top:4.12in;left:3.00in;width:2.59in;height:0.48in" src="ri_9.png" />
<img style="position:absolute;top:7.18in;left:3.45in;width:1.60in;height:0.01in" src="ri_10.png" />
<img style="position:absolute;top:9.02in;left:3.77in;width:4.11in;height:0.01in" src="ri_11.png" />
<img style="position:absolute;top:12.21in;left:1.09in;width:6.88in;height:0.02in" src="ri_12.png" />
<img style="position:absolute;top:12.27in;left:1.18in;width:0.19in;height:0.19in" src="ri_13.png" />
<img style="position:absolute;top:12.21in;left:1.27in;width:1.43in;height:0.28in" src="ri_14.png" />
<button  onClick="window.print()">Print this page
</button>
</body>
</html>
